baseURL = "https://tv.osgeo.nl/"
languageCode = "nl-nl"
title = "De Grote Geo Show"
theme = "ananke"
publishDir = "docs"

MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 3 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = ""
  description = "Descriptie"
  facebook = ""
  twitter = "https://twitter.com/osgeonl"
  instagram = ""
  youtube = "https://www.youtube.com/channel/UCvSAN6ur4RoGUqxtvmgsb8g"
  github = "https://github.com/osgeonl"
  gitlab = ""
  linkedin = ""
  mastodon = ""
  slack = ""
  stackoverflow = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-green"
  featured_image = "/images/dggs-logo1.jpg"
  recent_posts_number = 2
